### ISSUE TITLE
New CLHEP version 2.3.1.1

### ISSUE THREAD

**Issue by civanch** [cms-externals/clhep#1]
We need a new branch for CLHEP 2.3.1.1 , 
CLHEP can be upgraded using tar from CLHEP download page: http://proj-clhep.web.cern.ch/proj-clhep/DISTRIBUTION/

**Comment by Dr15Jones** [comment]
Do we have any thread safety fixes that we previously applied?

**Comment by civanch** [comment]
CLHEP 2.3 should have thread safety fixes, at least, this is declared.

**Comment by ghost** [comment]
@civanch @Dr15Jones Please check #2.
