### ISSUE TITLE
New CLHEP version 2.3.4.2

### ISSUE THREAD

**Issue by civanch** [cms-externals/clhep#3]
New CLHEP 2.3.4.2 include important fixes for random number generation.

A new branch in cms-externals/clhep will be needed. @smuzaffar , I likely have no permission to make a new branch, so cannot make PR myself.

**Comment by smuzaffar** [comment]
@civanch , why not 
   * 30.11.16 Release CLHEP-2.3.4.3: cmake: bug fix for the Intel compiler to allow multithreading

**Comment by smuzaffar** [comment]
@iahmad-khan , can you please take care of it?

**Comment by iahmad-khan** [comment]
@smuzaffar i think it has been merged already

**Comment by civanch** [comment]
@iahmad-khan , Thanks! I will try to proceed further.
