### ISSUE TITLE
Create a new branch for CLHEP 2.4.0.0

### ISSUE THREAD

**Issue by civanch** [cms-externals/clhep#4]
A new CLHEP 2.4.0.0 release become available: https://gitlab.cern.ch/CLHEP/CLHEP/tree/CLHEP_2_4_0_0 

It is c++17 compatible and includes random number generators updates. It is the recommended version for the new Geant4 10.4 but may be used with early Geant4 versions.

**Comment by civanch** [comment]
Hello, @smuzaffar, it seems that this request is forgotten. Here nothing urgent but worse to have this version available.

**Comment by smuzaffar** [comment]
@civanch , sorry about that. It is available now https://github.com/cms-externals/clhep/tree/cms/v2.4.0.0
